### ISSUE TITLE
No mount is added to the cart when selecting Ball S4 to the Hornet Ghost

### ISSUE THREAD

**Issue by daita** [dolkensp/unp4k#27]
![image](https://user-images.githubusercontent.com/1038617/100552851-4382a880-3279-11eb-9908-f42bf3b79ee5.png)

The Anvil F7C-S Hornet Ghost comes with no element to fit anything on the top-center slot of the ship. 
Currently, when selecting 'Ball 2xS2', the website add the _C4-160f S5 Hornet Ball Turret_ to the cart, which is good.
However, when selecting 'Ball S4', The _Specialty Hornet S5 VariPuck Mount_ is not added to the cart.

**Comment by peter-dolkens** [comment]
Hi,

I am not sure I understand? This project is only for extracting data from
the game files - it has nothing to do with the behavior of the game, or
website?

**Comment by daita** [comment]
yup, my bad 👍
