### ISSUE TITLE
Changes to Support Datacore V5

### ISSUE THREAD

**Issue by Dobranican** [dolkensp/unp4k#28]
Recent changes to the DCB has caused Unforge to fail with the following
`
Error converting Game.dcb: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'.
Parameter name: chars
`

**Comment by InX-Invader** [comment]
Further investigation leads to file version update from 4 to 5. From current investigation we believe that the offset of the stream position has changed either from the addition of more types in the header, or a change of one of the type sizes. 

Program errors out at cstring binaryreader extension, however that method is fine, it's just reading garbage data starting at offset 70C27E, correct offset for cstrings section is at 70E5E6.

Will comment more if anything else is found.

**Comment by InX-Invader** [comment]
Alrighty one more thing before bed, I appear to have found the issue. Version 5 only appeared to have changed the DataForgeDataMapping complex type's StructIndex and StructCount types to UInt32 from UInt16, so it was throwing off the whole file by about 8-9k bytes on the v5. Changing these member's types to UInt32 causes the program to function as intended!

I will make a fork with the change and maybe do a pull request sometime tomorrow for you to review.

**Comment by InX-Invader** [comment]
Datacore version 5 appears to read much slower than reading 8k additional bytes would suggest in the pull request I generated here:

https://github.com/dolkensp/unp4k/pull/29

Needs further investigation.

**Comment by peter-dolkens** [comment]
https://www.twitch.tv/videos/947472462 ;)

Was waiting for a wave1 before pushing.

I want to rewrite this entire thing into a streaming format at some point, but until then - enjoy the merge :)
