### ISSUE TITLE
Unable to Unforge and unpack Game.dcb since PTU 3.13

### ISSUE THREAD

**Issue by 1ch00** [dolkensp/unp4k#30]
Hi, 

I love your tool and I use it constantly :) . However, since PTU 3.13 I am not able anymore to unpack the Game.dcb. What am I doing wrong? It seems to me that there is an adjustment required in the tool?

![03-04-_2021_23-22-36](https://user-images.githubusercontent.com/63108997/113491855-0acb3800-94d4-11eb-97ac-9286753df43e.png)

Kind Regards

**Comment by 1ch00** [comment]
When will we see the adapted version for release? :)

**Comment by peter-dolkens** [comment]
Latest build should now be published - let me know if there's any further issues.

**Comment by 1ch00** [comment]
Yeah I saw you worked today on the new build. :) Works like a charm. Cheers. Already datamining stuff for SC Mining ^^
