### ISSUE TITLE
3.23 Exported character file analysis

### ISSUE THREAD

**Issue by diogotr7** [dolkensp/unp4k#56]
Hello!

I'd like to start off by saying that this isn't strictly about unp4k, but I hope it's close enough that you'll have some insight I do not, or at least point me towards a better place for me to investigate.

With the 3.23 EPTU patch, we can now save character files as `*.chf`. Some examples here: https://www.star-citizen-characters.com/

[According to CIG](https://youtu.be/XsEKbJmtuW4?si=RQFDUPSb-nkCK-GL&t=883), these files are encrypted and then compressed. Out of curiosity I dissected some of these files and am gathering research here: https://github.com/diogotr7/StarCitizenChf

So far I've managed to dissect the header for the file, the crc checksum check and the compression (zstd).

Trying to figure out the encryption seems like a much bigger can of worms to deal with which is why I'm making this issue.

I see unp4k has a hardcoded `key` in the code when unpacking crypack(?) files. Is this something that is standard to all cryengine games?  Is this something you had to reverse engineer out of the game? Do you have any advice for ways I could decrypt this?

Thanks for any insight, if you feel this is too offtopic of course feel free to close.

**Comment by Stryxus** [comment]
This is a universal cry engine key, I'm afraid. Shouldn't the cypher name be in the header? If not, it may be impossible/impractical to get which cypher is used.

**Comment by diogotr7** [comment]
I dont think the extracted buffer has anything interesting. The first 8 bytes I believe describe the version of the data. In this case the version is 7. I was not able to find any magic bytes in this data but maybe there's something I didn't see. Here is the default female character extracted:
![image](https://github.com/dolkensp/unp4k/assets/29486064/21679b25-1382-4afd-8385-2bfc69a19413)


I've used the same decryption `AesManaged` with the same key and options as in unp4k, I have a couple files that do decrypt successfully but i suspect this is a coincidence, the resulting data is not really useful.

**Comment by Stryxus** [comment]
> Edit: looking at data again the entropy seems far to low for it to actually be encrypted. It's possible that it's not. It might simply be a custom binary format?

That's certainly possible, most of that is outside my areas of expertise, though.

**Comment by peter-dolkens** [comment]
CryEngine has a standard way to do encryption which is what CIG uses.

The CryEngine binary has some key data which gets converted into the key data for various different algorithms at startup, so I actually extracted the key directly from memory rather than reading it from the binary.

Have you tried throwing unp4k or unforge at the files?

**Comment by diogotr7** [comment]
I managed to do this by simply altering bytes in this data:
![](https://cdn.discordapp.com/attachments/702227680090914866/1233440828941275216/image.png?ex=662d1ac9&is=662bc949&hm=131a56cd00b49eacb6e356e7fa9a0ecdbf76c0644881af527c9dc1a5ccd124ae)

So it's safe to say It's not actually encrypted :)

Closing, thanks for the guidance.
